import { MusicCategory, MusicTrack } from '../types';

export const MUSIC_TRACKS: MusicTrack[] = [
  {
    id: 'track-generative',
    title: 'Endless Lo-Fi Radio (Vinyl Chords)',
    artist: 'WebAudio Generative Synth (Royalty-Free / Offline)',
    category: 'lofi',
    url: 'generative',
    duration: 3600,
  },
  {
    id: 'track-1',
    title: 'Rainy Day Reverie',
    artist: 'Cozy Pixel Ensemble (Royalty-Free)',
    category: 'rainy',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=lofi-study-112191.mp3',
    duration: 147,
  },
  {
    id: 'track-2',
    title: 'Midnight Coffee & Hearth',
    artist: 'Chilled Velvet Beats (CC0)',
    category: 'lofi',
    url: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=tea-time-lofi-chill-14470.mp3',
    duration: 138,
  },
  {
    id: 'track-3',
    title: 'Warm Wool Sweater',
    artist: 'Autumn Leaves Project (Royalty-Free)',
    category: 'chillhop',
    url: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=lofi-chill-medium-version-124377.mp3',
    duration: 154,
  },
  {
    id: 'track-4',
    title: 'Old Books & Dusty Shelves',
    artist: 'Scholar Lounge (Royalty-Free)',
    category: 'study',
    url: 'https://cdn.pixabay.com/download/audio/2023/04/10/audio_55a29cceae.mp3?filename=chill-lofi-song-8444.mp3',
    duration: 162,
  },
  {
    id: 'track-5',
    title: 'Quiet Window View',
    artist: 'Nocturnal Keys (Royalty-Free)',
    category: 'piano',
    url: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c08790b5.mp3?filename=lofi-piano-beat-112521.mp3',
    duration: 130,
  },
  {
    id: 'track-6',
    title: 'Golden Hour Solitude',
    artist: 'Velvet Afternoon (Royalty-Free)',
    category: 'jazzhop',
    url: 'https://cdn.pixabay.com/download/audio/2022/01/26/audio_d0c6ff1101.mp3?filename=lazy-day-stylish-futuristic-chill-20924.mp3',
    duration: 145,
  },
  {
    id: 'track-7',
    title: 'Deep Midnight Focus',
    artist: 'Subtle Horizons (Royalty-Free)',
    category: 'deep_focus',
    url: 'https://cdn.pixabay.com/download/audio/2023/07/30/audio_108bb6b2e3.mp3?filename=chill-lo-fi-159495.mp3',
    duration: 172,
  },
  {
    id: 'track-8',
    title: 'Slumbering Feline',
    artist: 'Gentle Paws Lofi (Royalty-Free)',
    category: 'night',
    url: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_db6591201e.mp3?filename=lofi-orchestra-16230.mp3',
    duration: 128,
  },
  {
    id: 'track-9',
    title: 'Kyoto Bamboo Mist',
    artist: 'Eastern Zen Collective (CC0)',
    category: 'chillhop',
    url: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_c9a4490f2d.mp3?filename=japanese-chill-hop-125950.mp3',
    duration: 168,
  },
  {
    id: 'track-10',
    title: 'Cyberpunk Neon Drizzle',
    artist: 'Synthwave Midnight (Royalty-Free)',
    category: 'lofi',
    url: 'https://cdn.pixabay.com/download/audio/2023/02/28/audio_5b66d4825d.mp3?filename=cyber-rain-chill-141203.mp3',
    duration: 180,
  },
  {
    id: 'track-11',
    title: 'Sleeper Train Odyssey',
    artist: 'Orient Midnight Express (Royalty-Free)',
    category: 'night',
    url: 'https://cdn.pixabay.com/download/audio/2022/03/10/audio_c35272a2a0.mp3?filename=night-city-lofi-109062.mp3',
    duration: 158,
  },
  {
    id: 'track-12',
    title: 'Library Dust & Moonlight',
    artist: 'Acoustic Solitude (CC0)',
    category: 'piano',
    url: 'https://cdn.pixabay.com/download/audio/2022/04/27/audio_6fa6b1ec66.mp3?filename=soft-piano-meditation-111162.mp3',
    duration: 194,
  },
  {
    id: 'track-13',
    title: 'Cozy Campfire & Tea',
    artist: 'Acoustic Pine Ensemble (Royalty-Free)',
    category: 'study',
    url: 'https://cdn.pixabay.com/download/audio/2022/08/04/audio_34b07cfdc8.mp3?filename=campfire-lofi-117565.mp3',
    duration: 142,
  },
  {
    id: 'track-14',
    title: 'Vintage Record Player Memories',
    artist: 'Gramophone Nostalgia (Royalty-Free)',
    category: 'jazzhop',
    url: 'https://cdn.pixabay.com/download/audio/2022/06/07/audio_b72b8344dc.mp3?filename=vintage-vinyl-chill-112988.mp3',
    duration: 150,
  },
  {
    id: 'track-15',
    title: 'Autumn Wind in Shinjuku',
    artist: 'Tokyo Crossings (Royalty-Free)',
    category: 'rainy',
    url: 'https://cdn.pixabay.com/download/audio/2023/09/05/audio_15f79590da.mp3?filename=tokyo-autumn-lofi-165842.mp3',
    duration: 165,
  },
  {
    id: 'track-16',
    title: 'Deep Brainwave Flow',
    artist: 'Cognitive Alpha Harmonics (CC0)',
    category: 'deep_focus',
    url: 'https://cdn.pixabay.com/download/audio/2023/11/12/audio_49cbf64ef4.mp3?filename=deep-focus-ambient-176321.mp3',
    duration: 210,
  },
  {
    id: 'track-17',
    title: 'Steaming Mug of Cocoa',
    artist: 'Winter Cabin Lounge (Royalty-Free)',
    category: 'lofi',
    url: 'https://cdn.pixabay.com/download/audio/2022/12/15/audio_9ec1618335.mp3?filename=snowy-cabin-lofi-130985.mp3',
    duration: 149,
  },
  {
    id: 'track-18',
    title: 'Zen Garden Water Drops',
    artist: 'Tranquil Bamboo Suite (Royalty-Free)',
    category: 'chillhop',
    url: 'https://cdn.pixabay.com/download/audio/2023/01/10/audio_b2ff2524a8.mp3?filename=water-droplets-lofi-134211.mp3',
    duration: 175,
  },
  {
    id: 'track-19',
    title: 'Midnight Coding Flow',
    artist: 'Terminal Hackers (Royalty-Free)',
    category: 'study',
    url: 'https://cdn.pixabay.com/download/audio/2022/07/21/audio_1204d80a18.mp3?filename=coding-at-night-lofi-116120.mp3',
    duration: 184,
  },
  {
    id: 'track-20',
    title: 'Starlight Lullaby for Cats',
    artist: 'Velvet Purr Records (CC0)',
    category: 'piano',
    url: 'https://cdn.pixabay.com/download/audio/2023/05/18/audio_11202e21b8.mp3?filename=gentle-cat-piano-151042.mp3',
    duration: 198,
  },
  {
    id: 'track-21',
    title: 'Nordic Hearthside Ambient',
    artist: 'Alpine Solitude (Royalty-Free)',
    category: 'study',
    url: 'https://cdn.pixabay.com/download/audio/2022/10/25/audio_8241b12b5a.mp3?filename=winter-hearth-chill-124991.mp3',
    duration: 168,
  },
  {
    id: 'track-22',
    title: 'Rainy Shibuya Crossing',
    artist: 'Tokyo Puddle Beats (CC0)',
    category: 'rainy',
    url: 'https://cdn.pixabay.com/download/audio/2023/04/05/audio_8345e69bf8.mp3?filename=rain-in-tokyo-lofi-146312.mp3',
    duration: 156,
  },
  {
    id: 'track-23',
    title: 'Old Vinyl Dust & Coffee',
    artist: 'Gramophone Lounge (Royalty-Free)',
    category: 'jazzhop',
    url: 'https://cdn.pixabay.com/download/audio/2022/11/15/audio_73e4b7520b.mp3?filename=vinyl-dust-lofi-127110.mp3',
    duration: 144,
  },
  {
    id: 'track-24',
    title: 'Moonlit Library Stacks',
    artist: 'Gothic Folio Ensemble (Royalty-Free)',
    category: 'piano',
    url: 'https://cdn.pixabay.com/download/audio/2023/08/11/audio_6b9dc1035b.mp3?filename=midnight-piano-study-162388.mp3',
    duration: 192,
  },
  {
    id: 'track-25',
    title: 'Cyberpunk Rooftop Neon',
    artist: 'Synth Grid Runners (CC0)',
    category: 'night',
    url: 'https://cdn.pixabay.com/download/audio/2023/03/14/audio_34b127ffea.mp3?filename=neon-skyline-lofi-143099.mp3',
    duration: 178,
  },
  {
    id: 'track-26',
    title: 'Bonsai Tree Reverie',
    artist: 'Koto Ambient Collective (Royalty-Free)',
    category: 'chillhop',
    url: 'https://cdn.pixabay.com/download/audio/2022/09/20/audio_51cb0d31ef.mp3?filename=zen-garden-peace-121890.mp3',
    duration: 162,
  },
  {
    id: 'track-27',
    title: 'Late Night Commute',
    artist: 'Subway Sleeper (Royalty-Free)',
    category: 'jazzhop',
    url: 'https://cdn.pixabay.com/download/audio/2023/06/02/audio_967b5e40e2.mp3?filename=night-train-lofi-153401.mp3',
    duration: 170,
  },
  {
    id: 'track-28',
    title: 'Warm Fireplace Lofi',
    artist: 'Cozy Hearth Beats (CC0)',
    category: 'lofi',
    url: 'https://cdn.pixabay.com/download/audio/2022/12/01/audio_82c610e2eb.mp3?filename=fireplace-cozy-vibes-129480.mp3',
    duration: 154,
  },
  {
    id: 'track-29',
    title: 'Velvet Midnight Keys',
    artist: 'Nocturnal Solitude (Royalty-Free)',
    category: 'piano',
    url: 'https://cdn.pixabay.com/download/audio/2023/10/08/audio_24db8a36ef.mp3?filename=velvet-keys-piano-169820.mp3',
    duration: 186,
  },
  {
    id: 'track-30',
    title: 'Alpha Flow Gamma State',
    artist: 'Binaural Harmony Labs (CC0)',
    category: 'deep_focus',
    url: 'https://cdn.pixabay.com/download/audio/2023/12/04/audio_98af21cb12.mp3?filename=gamma-focus-waves-179830.mp3',
    duration: 220,
  },
];

export const MUSIC_CATEGORIES: { id: MusicCategory; label: string }[] = [
  { id: 'all', label: 'All Beats' },
  { id: 'lofi', label: 'Lo-Fi' },
  { id: 'chillhop', label: 'Chillhop' },
  { id: 'jazzhop', label: 'Jazzhop' },
  { id: 'piano', label: 'Piano' },
  { id: 'rainy', label: 'Rainy Day' },
  { id: 'night', label: 'Midnight' },
  { id: 'study', label: 'Study' },
  { id: 'deep_focus', label: 'Deep Focus' },
];
